name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test

      - name: Determine publish tag
        id: tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $VERSION"
          if [[ $VERSION =~ -[a-zA-Z] ]]; then
            echo "tag=alpha" >> $GITHUB_OUTPUT
            echo "Publishing as pre-release with alpha tag"
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "Publishing as stable release with latest tag"
          fi

      - name: Verify NPM authentication
        run: |
          echo "Checking NPM authentication..."
          if npm whoami; then
            echo "✅ NPM authentication successful"
            echo "Current user: $(npm whoami)"
          else
            echo "❌ NPM authentication failed"
            echo "Please check if NPM_TOKEN is valid and has proper permissions"
            exit 1
          fi
          
          echo "Checking package access permissions..."
          if npm access ls-packages 2>/dev/null; then
            echo "✅ Package access check completed"
          else
            echo "⚠️  Package access check failed (this may be normal for new tokens)"
            echo "Continuing with publish attempt..."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if version exists
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Checking if version $VERSION already exists on NPM..."
          if npm view s3-zip@$VERSION version 2>/dev/null; then
            echo "⚠️  Version $VERSION already exists on NPM"
            echo "Please update the version number in package.json"
            exit 1
          else
            echo "✅ Version $VERSION is available for publishing"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dry run publish
        run: |
          echo "Running npm publish dry-run to validate package..."
          npm publish --tag ${{ steps.tag.outputs.tag }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --tag ${{ steps.tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}