name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test

      - name: Determine publish tag
        id: tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $VERSION"
          if [[ $VERSION =~ -[a-zA-Z] ]]; then
            echo "tag=alpha" >> $GITHUB_OUTPUT
            echo "Publishing as pre-release with alpha tag"
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "Publishing as stable release with latest tag"
          fi

      - name: Verify NPM authentication
        run: |
          echo "Checking NPM authentication..."
          npm whoami
          echo "Checking package access permissions..."
          npm access ls-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dry run publish
        run: |
          echo "Running npm publish dry-run to validate package..."
          npm publish --tag ${{ steps.tag.outputs.tag }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --tag ${{ steps.tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}